### ISSUE TITLE
S3 Export halts on invalid symlinks

### ISSUE THREAD

**Issue by garethmidwood** [thaiphan/magento-s3#2]
When a media file is actually a symlink and the target file does not exist then the s3_export script halts with no explanation.

Perhaps it should skip the file and offer an error report at the end, or fail immediately with an error?

**Comment by thaiphan** [comment]
Hi @garethmidwood,

I have applied a partial fix to address exports to S3 failing on broken symlinks. The command line tool should now just ignore broken symlinks. However, the admin interface was too difficult to address since it requires overriding some more core functionality that I'm not comfortable doing at the point in time.

Regards,

Thai
